# Generated by Django 4.0.5 on 2022-06-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='image')),
                ('titulo', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Aed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Cg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=120)),
                ('disciplina', models.CharField(max_length=120)),
                ('texto', models.TextField(max_length=16620)),
            ],
        ),
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='image')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Home_projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Home_Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='image')),
                ('titulo', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Interesses_hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=20)),
                ('link', models.URLField(max_length=120)),
                ('disciplina', models.CharField(max_length=120)),
                ('texto', models.TextField(max_length=16620)),
            ],
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=120)),
                ('disciplina', models.CharField(max_length=120)),
                ('semestre', models.CharField(max_length=200)),
                ('ect', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('titulo1', models.CharField(max_length=200)),
                ('texto1', models.TextField()),
                ('titulo2', models.CharField(max_length=200)),
                ('texto2', models.TextField()),
                ('titulo3', models.CharField(max_length=200)),
                ('texto3', models.TextField()),
                ('professor', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lp1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Outras_Habilitacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=120)),
                ('disciplina', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='OutSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('texto', models.TextField(max_length=20000)),
                ('texto2', models.TextField(max_length=20000)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=202)),
                ('subtitulo', models.CharField(max_length=204)),
                ('texto', models.TextField(max_length=20000)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='image')),
                ('titulo', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
